### ISSUE TITLE
Return code is always 1, even when no issues are found

### ISSUE THREAD

**Issue by LoicGombeaud** [lukaszraczylo/salt-lint#10]
Hello, thank you for this gem!

I would like to use it in our CI/CD pipeline, but am running into an issue: the return code is always 1, even where no issues are found. I've read the code to try to understand why, but could not find the issue.

I would very much appreciate if you have the time to look into it! Let me know if you need additional information.

**Comment by dijit** [comment]
Oh, I just submitted a duplicate of this and a fix, issue #11 PR https://github.com/lukaszraczylo/salt-lint/pull/12

**Comment by LoicGombeaud** [comment]
Thanks!
