### ISSUE TITLE
Exit codes

### ISSUE THREAD

**Issue by aknapp** [lukaszraczylo/salt-lint#8]
The `salt-lint` executable always returns `0`, even if something has failed. Are there plans to actually return correct codes? Also have to think of the case when using `-s` also.

**Comment by michalschott** [comment]
I have faced the same problem, potential fix - https://github.com/lukaszraczylo/salt-lint/pull/9

**Comment by lukaszraczylo** [comment]
PR#9 merged into master and released via rubygems
